import {
  Robot,
  Station,
  Package,
  FactoryAgent,
  MCPTool,
  MCPToolCallLog,
  PipelineStage,
  FactoryEvent,
  A2APacketAnimation,
  FactoryAnalyticsData,
  SecurityStatus
} from '../types/factory';

export const INITIAL_STATIONS: Station[] = [
  { id: 'raw_material', name: 'Raw Material Storage', code: 'STN-01', icon: 'PackageCheck', status: 'IDLE', capacity: 10, itemCount: 4 },
  { id: 'assembly', name: 'Robotic Assembly Area', code: 'STN-02', icon: 'Wrench', status: 'IDLE', capacity: 5, itemCount: 0 },
  { id: 'inspection', name: '6G Laser Inspection', code: 'STN-03', icon: 'Scan', status: 'IDLE', capacity: 5, itemCount: 0 },
  { id: 'packaging', name: 'Automated Packaging', code: 'STN-04', icon: 'BoxSelect', status: 'IDLE', capacity: 10, itemCount: 0 },
];

export const INITIAL_ROBOTS: Robot[] = [
  {
    id: 'R01',
    name: 'Robot R01 (Material Transfer)',
    agentId: 'ue_agent_001',
    status: 'IDLE',
    location: 'raw_material',
    x: 18,
    y: 42,
    battery: 98,
    speed: 1.5,
    skill: 'pick_and_place',
    maxPayloadKg: 50.0,
    oauthStatus: 'AUTHENTICATED',
    mcpAccess: true,
    imsi: '001010123456789',
    imei: 'imei-123456789',
    lastAction: 'Standing by at Raw Material Station',
    lastActionTime: '10:42:01',
  },
  {
    id: 'R02',
    name: 'Robot R02 (Assembly Operator)',
    agentId: 'ue_agent_002',
    status: 'IDLE',
    location: 'assembly',
    x: 48,
    y: 42,
    battery: 89,
    speed: 1.8,
    skill: 'welding_and_transfer',
    maxPayloadKg: 35.0,
    oauthStatus: 'AUTHENTICATED',
    mcpAccess: true,
    imsi: '001010000000001',
    imei: '356938035643809',
    lastAction: 'Idle at Assembly Station',
    lastActionTime: '10:42:05',
  },
  {
    id: 'R03',
    name: 'Robot R03 (Quality Scanner)',
    agentId: 'ue_agent_003',
    status: 'IDLE',
    location: 'inspection',
    x: 78,
    y: 42,
    battery: 94,
    speed: 2.1,
    skill: 'inspection_and_packaging',
    maxPayloadKg: 20.0,
    oauthStatus: 'AUTHENTICATED',
    mcpAccess: true,
    imsi: '001010000000002',
    imei: '864201937401928',
    lastAction: 'Calibrated 6G Laser Optics',
    lastActionTime: '10:41:50',
  },
];

export const INITIAL_AGENTS: FactoryAgent[] = [
  { id: 'supervisor-01', name: 'Supervisor Agent', role: 'Supervisor', port: 8000, state: 'ACTIVE', skills: ['orchestrate', 'task-planning'], lastAction: 'Monitoring factory operations', lastActionTime: '10:42:10', oauthStatus: 'AUTHORIZED', trustScore: 99 },
  { id: 'ausf-01', name: 'AUSF Agent', role: 'AUSF', port: 8001, state: 'ACTIVE', skills: ['auth', 'aka-challenge'], lastAction: 'Agent-AKA verification ready', lastActionTime: '10:40:00', oauthStatus: 'AUTHORIZED', trustScore: 100 },
  { id: 'udm-01', name: 'UDM Agent', role: 'UDM', port: 8003, state: 'ACTIVE', skills: ['subscriber-profile', 'auth-vectors'], lastAction: 'Profiles synchronized', lastActionTime: '10:41:00', oauthStatus: 'AUTHORIZED', trustScore: 100 },
  { id: 'security-01', name: 'Security Agent', role: 'Security', port: 8105, state: 'ACTIVE', skills: ['trust-scoring', 'risk-eval'], lastAction: 'Zero trust security active', lastActionTime: '10:42:00', oauthStatus: 'AUTHORIZED', trustScore: 98 },
  { id: 'r1-agent', name: 'Robot Agent R1', role: 'Robot', port: 8004, state: 'ACTIVE', skills: ['pick_and_place'], lastAction: 'Ready for assignment', lastActionTime: '10:42:01', oauthStatus: 'AUTHORIZED', trustScore: 95, imsi: '001010123456789' },
  { id: 'r2-agent', name: 'Robot Agent R2', role: 'Robot', port: 8107, state: 'ACTIVE', skills: ['welding_and_transfer'], lastAction: 'Ready for assignment', lastActionTime: '10:42:05', oauthStatus: 'AUTHORIZED', trustScore: 92, imsi: '001010000000001' },
  { id: 'r3-agent', name: 'Robot Agent R3', role: 'Robot', port: 8108, state: 'ACTIVE', skills: ['inspection_and_packaging'], lastAction: 'Ready for assignment', lastActionTime: '10:41:50', oauthStatus: 'AUTHORIZED', trustScore: 97, imsi: '001010000000002' },
];

export const AVAILABLE_MCP_TOOLS: MCPTool[] = [
  { name: 'get_factory_status()', description: 'Read seeded station and conveyor state from the local demo; this is not live telemetry.', category: 'factory' },
  { name: 'get_robot_status()', description: 'Read sample robot availability, battery, location, and payload values from the local demo.', category: 'robot' },
  { name: 'dispatch_robot()', description: 'Simulate a robot assignment in local demo state; no hardware command is sent.', category: 'robot' },
  { name: 'stop_robot()', description: 'Simulate a local stopped state; this does not send an emergency-stop command to hardware.', category: 'robot' },
  { name: 'authenticate_agent()', description: 'Show sample authentication state; this does not perform Keycloak or Agent-AKA validation.', category: 'auth' },
  { name: 'assign_task()', description: 'Simulate a manufacturing task assignment in local demo state.', category: 'factory' },
  { name: 'get_package_status()', description: 'Read sample package position and progress from the local demo.', category: 'factory' },
  { name: 'move_package()', description: 'Simulate package movement between workstation zones; no conveyor is controlled.', category: 'factory' },
];

export const INITIAL_PIPELINE: PipelineStage[] = [
  { id: 'cmd', label: 'USER COMMAND', status: 'PENDING', detail: 'Awaiting natural language input' },
  { id: 'llm', label: 'LLM ANALYSIS', status: 'PENDING', detail: 'Tool & intent parsing' },
  { id: 'sup', label: 'SUPERVISOR AGENT', status: 'PENDING', detail: 'Workflow decomposition' },
  { id: 'disc', label: 'AGENT DISCOVERY', status: 'PENDING', detail: 'Registry skill lookup' },
  { id: 'mcp_sel', label: 'MCP TOOL SELECTION', status: 'PENDING', detail: 'Matching tool signature' },
  { id: 'oauth', label: 'OAUTH AUTHENTICATION', status: 'PENDING', detail: 'Keycloak token verify' },
  { id: 'mcp_exec', label: 'MCP TOOL EXECUTION', status: 'PENDING', detail: 'FastMCP RPC payload' },
  { id: 'robot', label: 'ROBOT AGENT', status: 'PENDING', detail: 'Robot movement & action' },
  { id: 'action', label: 'FACTORY ACTION', status: 'PENDING', detail: 'Conveyor & Station update' },
  { id: 'complete', label: 'TASK COMPLETED', status: 'PENDING', detail: 'Order fulfilled 100%' },
];
